### ISSUE TITLE
spelling mistake

### ISSUE THREAD

**Issue by sg-milad** [SeyedMostafaHosseinian/Nest-blog-app#1]
Hello Mostafa,

I want to express my gratitude for your project, which has been incredibly helpful. However, I noticed that there are quite a few spelling mistakes in it. Could you please fix them? Thank you.
![image](https://github.com/SeyedMostafaHosseinian/Nest-blog-app/assets/96006331/39872ada-c9a5-4d42-a240-b3fbc36b84cc)
![image](https://github.com/SeyedMostafaHosseinian/Nest-blog-app/assets/96006331/ca83cdc4-a181-4f27-9f59-5e9f7a827d8f)

I suggest you install this [extension](https://marketplace.visualstudio.com/items?itemName=streetsidesoftware.code-spell-checker)

**Comment by SeyedMostafaHosseinian** [comment]
> Hello Mostafa,
> 
> I want to express my gratitude for your project, which has been incredibly helpful. However, I noticed that there are quite a few spelling mistakes in it. Could you please fix them? Thank you. ![image](https://private-user-images.githubusercontent.com/96006331/302031159-39872ada-c9a5-4d42-a240-b3fbc36b84cc.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDY5ODQxOTMsIm5iZiI6MTcwNjk4Mzg5MywicGF0aCI6Ii85NjAwNjMzMS8zMDIwMzExNTktMzk4NzJhZGEtYzlhNS00ZDQyLWEyNDAtYjNmYmMzNmI4NGNjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMDMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjAzVDE4MTEzM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTY3NTc0ZTRlNTdhZmM3MDdiODViMDk5Y2EwMGY4M2M3OWQwYzExNjdlNmNiMDM1MjUxMDYyZDczZjk0ZmI3MDkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.aFhIFwOdrKyCnaY-KSnXw6HanzumqU9f-qEU_yYHSGo) ![image](https://private-user-images.githubusercontent.com/96006331/302031179-ca83cdc4-a181-4f27-9f59-5e9f7a827d8f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDY5ODQxOTMsIm5iZiI6MTcwNjk4Mzg5MywicGF0aCI6Ii85NjAwNjMzMS8zMDIwMzExNzktY2E4M2NkYzQtYTE4MS00ZjI3LTlmNTktNWU5ZjdhODI3ZDhmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMDMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjAzVDE4MTEzM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTY4YzIzZmQwOTJlOWY4ODQzMWY4OWY4YzViMDJhZWY0NjYxNjBjNDBiYTdmN2FjOTkzMGQ3ODE3NzQ3N2NiNjMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.JuBBl3nqjnkIOL_W-qlMPtiHlvtTR-SrFneKl0WtXsc)
> 
> I suggest you install this [extension](https://marketplace.visualstudio.com/items?itemName=streetsidesoftware.code-spell-checker)


hello my friend thanks for you comment and suggestions. I did the necessary checks and corrected them. good luck 🌹
